### PR TITLE
Add gRPC layer

### PR DESCRIPTION
**Pull request by thedodd**
Hello, I'm sure there is a bunch of stuff you will want me to do to get this ready for merge. I'm happy to do so. I just wanted to open this and ping for review. Thanks for putting this together. It is already working quite nicely with Tonic & Axum (thanks to the shared tower foundation).

### CODE REVIEW

**Comment by davidB** [comment]
Thanks for PR.

Can you include a test (or an example) to show / to validate the code  ?

**Comment by thedodd** [comment]
Will do! Need to circle back here soon. I'll address the linter items as well.

**Comment by davidB** [comment]
I'll take care the linter issue, it'not due to your PR.

**Comment by zeeshanlakhani** [comment]
Howdy, just checking in on this and wondering if there's a path toward this getting in vs implementing something internally. Does it only need a test + example? cc @thedodd @davidB

**Comment by thedodd** [comment]
I should be able to come back to this code this week.

**Comment by zeeshanlakhani** [comment]
@thedodd awesome.

**Comment by thedodd** [comment]
Ok, looks like we are g2g now.

**Review by davidB — APPROVED** [review]
If I want to test/play with grpc+axum (and your PR ;-) ), do you have a link to a tutorial / example to recommend ? 

(Optional) you can modify the README.md to notify about the grpc feature. (I'll merge at the end of the next weekend, and probably do a release next week)

Thanks

**Comment by thedodd** [comment]
In a subsequent PR, I'll add an example with some basic usage, and then I'll also update the readme. I'll have time to do this tomorrow.

**Pull request merged**
